version: 2

sources:
  - name: google_drive_schema
    database: LOAD
    schema: GOOGLE_DRIVE_SCHEMA
    tables:
      - name: EXPENSES
        config:
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}