version: 2

sources:
  - name: google_drive_schema
    database: LOAD
    schema: GOOGLE_DRIVE_SCHEMA
    tables:
      - name: EXPENSES
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}

      - name: HR_JOINS
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}

      - name: HR_QUITS
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}

      - name: HR_RETURNS
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 48, period: hour}
            error_after: {count: 72, period: hour}

  - name: web_schema
    database: LOAD
    schema: WEB_SCHEMA
    tables:
      - name: ITEM_VIEWS
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}

      - name: ORDERS
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}

      - name: PAGE_VIEWS
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}

      - name: SESSIONS
        config:
          loaded_at_field: _FIVETRAN_SYNCED
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}